---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.2.2
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: false
    checksum: false
    download: false
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: true
    system: false
    tags: true
    version: false
app_desc: Install and Run Python Applications in Isolated Environments
app_name: pipx
app_repo: https://github.com/pypa/pipx
app_type: python
app_website: https://pypa.github.io/pipx/
checksum_enabled: false
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: python
gpg_enabled: false
install_map_enabled: true
install_map_method: link
install_map_yaml:
    venv/bin/pipx: bin/pipx
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-pipx
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-pipx.git
python_name: pipx
source_enabled: true
source_type: git
source_url: https://github.com/pypa/pipx
test_cmd_args: --version
version_file_enabled: false
version_prefix: ''
